networks:
  node-network:
    driver: bridge

services:
  db:
    platform: linux/x86_64
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: nodedb
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    networks:
      - node-network

  app:
    depends_on:
      - "db"
    build:
      context: node
    container_name: app
    volumes:
      - ./node:/usr/src/app
    networks:
      - node-network
    tty: true
    entrypoint:
      [
        "dockerize",
        "-wait",
        "tcp://db:3306",
        "-timeout",
        "20s",
        "node",
        "app.js",
      ]

  nginx:
    depends_on:
      - "app"
    build:
      context: nginx
    container_name: nginx
    expose:
      - "8080"
    ports:
      - "8080:8080"
    networks:
      - node-network
    tty: true
    entrypoint:
      [
        "dockerize",
        "-wait",
        "tcp://app:3000",
        "-timeout",
        "20s",
        "nginx",
        "-g",
        "daemon off;",
      ]
